/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PesquisaTransicaoCarreiraRouteImport } from './routes/pesquisa-transicao-carreira'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PerfilSlugRouteImport } from './routes/perfil.$slug'
import { Route as MateriaSlugRouteImport } from './routes/materia.$slug'
import { Route as InstitucionalPageRouteImport } from './routes/institucional.$page'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminPesquisaRouteImport } from './routes/admin.pesquisa'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMateriasNovaRouteImport } from './routes/admin.materias.nova'
import { Route as AdminMateriasSlugRouteImport } from './routes/admin.materias.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaTransicaoCarreiraRoute =
  PesquisaTransicaoCarreiraRouteImport.update({
    id: '/pesquisa-transicao-carreira',
    path: '/pesquisa-transicao-carreira',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilSlugRoute = PerfilSlugRouteImport.update({
  id: '/perfil/$slug',
  path: '/perfil/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaSlugRoute = MateriaSlugRouteImport.update({
  id: '/materia/$slug',
  path: '/materia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalPageRoute = InstitucionalPageRouteImport.update({
  id: '/institucional/$page',
  path: '/institucional/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesquisaRoute = AdminPesquisaRouteImport.update({
  id: '/admin/pesquisa',
  path: '/admin/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMateriasNovaRoute = AdminMateriasNovaRouteImport.update({
  id: '/admin/materias/nova',
  path: '/admin/materias/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMateriasSlugRoute = AdminMateriasSlugRouteImport.update({
  id: '/admin/materias/$slug',
  path: '/admin/materias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/pesquisa-transicao-carreira': typeof PesquisaTransicaoCarreiraRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pesquisa': typeof AdminPesquisaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/institucional/$page': typeof InstitucionalPageRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/materias/$slug': typeof AdminMateriasSlugRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/pesquisa-transicao-carreira': typeof PesquisaTransicaoCarreiraRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pesquisa': typeof AdminPesquisaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/institucional/$page': typeof InstitucionalPageRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/materias/$slug': typeof AdminMateriasSlugRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/pesquisa-transicao-carreira': typeof PesquisaTransicaoCarreiraRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pesquisa': typeof AdminPesquisaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/institucional/$page': typeof InstitucionalPageRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/materias/$slug': typeof AdminMateriasSlugRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/news-sitemap.xml'
    | '/pesquisa-transicao-carreira'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/login'
    | '/admin/pesquisa'
    | '/categoria/$slug'
    | '/institucional/$page'
    | '/materia/$slug'
    | '/perfil/$slug'
    | '/admin/'
    | '/admin/materias/$slug'
    | '/admin/materias/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/news-sitemap.xml'
    | '/pesquisa-transicao-carreira'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/login'
    | '/admin/pesquisa'
    | '/categoria/$slug'
    | '/institucional/$page'
    | '/materia/$slug'
    | '/perfil/$slug'
    | '/admin'
    | '/admin/materias/$slug'
    | '/admin/materias/nova'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/news-sitemap.xml'
    | '/pesquisa-transicao-carreira'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/login'
    | '/admin/pesquisa'
    | '/categoria/$slug'
    | '/institucional/$page'
    | '/materia/$slug'
    | '/perfil/$slug'
    | '/admin/'
    | '/admin/materias/$slug'
    | '/admin/materias/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  PesquisaTransicaoCarreiraRoute: typeof PesquisaTransicaoCarreiraRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPesquisaRoute: typeof AdminPesquisaRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  InstitucionalPageRoute: typeof InstitucionalPageRoute
  MateriaSlugRoute: typeof MateriaSlugRoute
  PerfilSlugRoute: typeof PerfilSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMateriasSlugRoute: typeof AdminMateriasSlugRoute
  AdminMateriasNovaRoute: typeof AdminMateriasNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-transicao-carreira': {
      id: '/pesquisa-transicao-carreira'
      path: '/pesquisa-transicao-carreira'
      fullPath: '/pesquisa-transicao-carreira'
      preLoaderRoute: typeof PesquisaTransicaoCarreiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$slug': {
      id: '/perfil/$slug'
      path: '/perfil/$slug'
      fullPath: '/perfil/$slug'
      preLoaderRoute: typeof PerfilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materia/$slug': {
      id: '/materia/$slug'
      path: '/materia/$slug'
      fullPath: '/materia/$slug'
      preLoaderRoute: typeof MateriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional/$page': {
      id: '/institucional/$page'
      path: '/institucional/$page'
      fullPath: '/institucional/$page'
      preLoaderRoute: typeof InstitucionalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pesquisa': {
      id: '/admin/pesquisa'
      path: '/admin/pesquisa'
      fullPath: '/admin/pesquisa'
      preLoaderRoute: typeof AdminPesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/materias/nova': {
      id: '/admin/materias/nova'
      path: '/admin/materias/nova'
      fullPath: '/admin/materias/nova'
      preLoaderRoute: typeof AdminMateriasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/materias/$slug': {
      id: '/admin/materias/$slug'
      path: '/admin/materias/$slug'
      fullPath: '/admin/materias/$slug'
      preLoaderRoute: typeof AdminMateriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  PesquisaTransicaoCarreiraRoute: PesquisaTransicaoCarreiraRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPesquisaRoute: AdminPesquisaRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  InstitucionalPageRoute: InstitucionalPageRoute,
  MateriaSlugRoute: MateriaSlugRoute,
  PerfilSlugRoute: PerfilSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMateriasSlugRoute: AdminMateriasSlugRoute,
  AdminMateriasNovaRoute: AdminMateriasNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
