INSERT INTO public.materias (
  slug, titulo, subtitulo, resumo, conteudo, categoria_id, autor_id, status,
  publicado_em, tempo_leitura, imagem, legenda_imagem, credito_imagem,
  classificacao, destaque, manchete, visualizacoes, fontes, resumo_rapido, ta_sabendo_disso, tags
) VALUES (
  'lucro-fgts-2026-quem-recebe-calculo',
  'Lucro do FGTS 2026: veja quem recebe e calcule o valor',
  'Caixa distribuirá R$ 13,04 bilhões para aproximadamente 138 milhões de trabalhadores; crédito está previsto para a primeira quinzena de agosto.',
  'Caixa distribuirá R$ 13,04 bilhões do lucro do FGTS. Veja quem tem direito, quando será depositado e como calcular quanto receberá.',
  ARRAY[
    'O saldo de milhões de trabalhadores brasileiros vai aumentar em agosto. O Conselho Curador do FGTS aprovou a distribuição de R$ 13,04 bilhões do resultado obtido pelo fundo em 2025.',
    'A medida deve beneficiar aproximadamente 138,2 milhões de trabalhadores que possuíam dinheiro em contas ativas ou inativas do FGTS em 31 de dezembro de 2025.',
    'O valor representa 89% do lucro de R$ 14,7 bilhões registrado pelo fundo no ano passado. Segundo o Ministério do Trabalho e Emprego, os créditos estão previstos para a primeira quinzena de agosto.',
    'Quem tem direito ao lucro do FGTS?',
    'Receberá o valor quem tinha saldo em uma ou mais contas do FGTS em 31 de dezembro de 2025. Isso inclui contas ativas, vinculadas ao emprego atual; inativas, relacionadas a empregos anteriores; com saldo parcialmente bloqueado; e de trabalhadores que sacaram o dinheiro após a data considerada.',
    'O pagamento será automático. Não é necessário fazer cadastro ou solicitação.',
    'Quanto cada trabalhador receberá?',
    'Não existe um pagamento igual para todos. O valor depende do saldo existente em cada conta no último dia de 2025. Para calcular, basta multiplicar esse saldo por 0,01868341.',
    'Simulação: saldo de R$ 1.000 rende cerca de R$ 18,68; R$ 3.000, cerca de R$ 56,05; R$ 5.000, cerca de R$ 93,42; R$ 10.000, cerca de R$ 186,83; e R$ 20.000, cerca de R$ 373,67.',
    'A própria Caixa Econômica Federal utiliza como exemplo um trabalhador que tinha R$ 10 mil: ele receberá aproximadamente R$ 186,83.',
    'Quando o dinheiro será depositado?',
    'A previsão oficial é que os créditos sejam realizados na primeira quinzena de agosto, depois da publicação da resolução no Diário Oficial da União. O dinheiro será adicionado diretamente ao saldo das contas do FGTS.',
    'Como consultar o pagamento?',
    'A consulta poderá ser feita pelo aplicativo FGTS. Clientes da Caixa também poderão verificar o extrato pelo Internet Banking. No extrato, o crédito deverá aparecer com a descrição “AC CRED DIST RESULTADO ANO BASE 12/2025”.',
    'O dinheiro poderá ser sacado imediatamente?',
    'Não necessariamente. O lucro passa a integrar o saldo do FGTS, mas continua sujeito às regras de saque do fundo. A liberação ocorre em situações previstas em lei, como demissão sem justa causa, aposentadoria, compra da casa própria e saque-aniversário.',
    'Ou seja: o saldo aumenta, mas isso não significa dinheiro livre na conta bancária. Manchete que esconde essa parte está vendendo fumaça.',
    'Perguntas frequentes',
    'Quem não está trabalhando recebe? Pode receber. O critério é ter possuído saldo em uma conta do FGTS em 31 de dezembro de 2025, mesmo que ela esteja inativa.',
    'Quem sacou o FGTS em 2026 ainda tem direito? Sim, desde que tivesse saldo na data de referência usada no cálculo.',
    'É necessário solicitar o pagamento? Não. O crédito será feito automaticamente.',
    'O lucro será depositado na conta bancária? Não. O valor será adicionado à conta vinculada do FGTS.',
    'Onde consultar? No aplicativo oficial FGTS ou, para clientes da Caixa, pelo Internet Banking.'
  ],
  '2a7c4d8f-153c-4b8b-9e1d-98943dcc3c28',
  'e76354dd-3f3b-4096-ab32-f427726ebc79',
  'Publicada',
  '2026-07-29T09:00:00-03:00',
  5,
  'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&h=800&q=80',
  'Aplicativo FGTS exibido em celular ao lado de notas de reais',
  'Unsplash',
  'Confirmado',
  true,
  true,
  0,
  '[{"titulo":"Ministério do Trabalho e Emprego","url":"https://www.gov.br/trabalho-e-emprego/pt-br"},{"titulo":"Caixa Econômica Federal","url":"https://www.caixa.gov.br/beneficios-trabalhador/fgts"}]'::jsonb,
  '{"quem":"Trabalhadores com saldo no FGTS em 31 de dezembro de 2025","oQue":"Foi aprovada a distribuição de R$ 13,04 bilhões","quando":"Primeira quinzena de agosto","situacao":"Confirmada","fontePrincipal":"Ministério do Trabalho e Caixa"}'::jsonb,
  'Com a distribuição do resultado, a rentabilidade total das contas do FGTS em 2025 chegou a 6,90% — 2,53 pontos percentuais acima da inflação oficial do período, segundo o Ministério do Trabalho.',
  ARRAY['lucro do FGTS 2026','FGTS','Caixa Econômica Federal','distribuição de lucros','saque FGTS','dinheiro']
);